-- Mind Over Matter newsletter and security hardening
-- Run once in Supabase Dashboard > SQL Editor after supabase-upgrade.sql
-- and supabase-books.sql. Safe to run again.

begin;

create extension if not exists pgcrypto;

create table if not exists public.newsletter_subscriptions (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  subscribed boolean not null default false,
  essays boolean not null default true,
  books boolean not null default true,
  consented_at timestamptz,
  consent_source text,
  unsubscribed_at timestamptz,
  unsubscribe_token uuid not null default gen_random_uuid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists newsletter_email_key
  on public.newsletter_subscriptions (lower(email));
create unique index if not exists newsletter_unsubscribe_token_key
  on public.newsletter_subscriptions (unsubscribe_token);
create index if not exists newsletter_active_topics_idx
  on public.newsletter_subscriptions (subscribed, essays, books);

create table if not exists public.newsletter_deliveries (
  id bigint generated by default as identity primary key,
  content_type text not null check (content_type in ('essay', 'book')),
  content_id bigint not null,
  status text not null default 'sending' check (status in ('sending', 'sent', 'failed')),
  subject text,
  recipient_count integer not null default 0 check (recipient_count >= 0),
  provider_ids jsonb,
  error_message text,
  sent_at timestamptz,
  created_at timestamptz not null default now(),
  unique (content_type, content_id)
);

create or replace function public.track_newsletter_preference()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();

  -- Signed-in readers may change only their consent and topic preferences.
  -- Protected identity/audit fields are maintained by trusted triggers.
  if (select auth.uid()) is not null and pg_trigger_depth() = 1 then
    new.user_id = old.user_id;
    new.email = old.email;
    new.unsubscribe_token = old.unsubscribe_token;
    new.created_at = old.created_at;
    new.consented_at = old.consented_at;
    new.consent_source = old.consent_source;
    new.unsubscribed_at = old.unsubscribed_at;
  end if;

  if new.subscribed is true and old.subscribed is false then
    new.consented_at = now();
    new.consent_source = 'reader_account';
    new.unsubscribed_at = null;
  elsif new.subscribed is false and old.subscribed is true then
    new.unsubscribed_at = now();
  end if;

  return new;
end;
$$;

drop trigger if exists track_newsletter_preference on public.newsletter_subscriptions;
create trigger track_newsletter_preference
before update on public.newsletter_subscriptions
for each row execute function public.track_newsletter_preference();

create or replace function public.handle_new_newsletter_reader()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  opted_in boolean := lower(coalesce(new.raw_user_meta_data ->> 'newsletter_opt_in', 'false')) = 'true';
begin
  insert into public.newsletter_subscriptions (
    user_id,
    email,
    subscribed,
    essays,
    books,
    consented_at,
    consent_source
  ) values (
    new.id,
    coalesce(new.email, ''),
    opted_in,
    true,
    true,
    case when opted_in then now() else null end,
    case when opted_in then 'reader_signup' else null end
  )
  on conflict (user_id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_newsletter on auth.users;
create trigger on_auth_user_newsletter
after insert on auth.users
for each row execute function public.handle_new_newsletter_reader();

create or replace function public.sync_newsletter_reader_email()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  update public.newsletter_subscriptions
  set email = coalesce(new.email, ''), updated_at = now()
  where user_id = new.id;
  return new;
end;
$$;

drop trigger if exists on_auth_user_email_changed on auth.users;
create trigger on_auth_user_email_changed
after update of email on auth.users
for each row
when (old.email is distinct from new.email)
execute function public.sync_newsletter_reader_email();

insert into public.newsletter_subscriptions (user_id, email, subscribed)
select id, coalesce(email, ''), false
from auth.users
on conflict (user_id) do nothing;

alter table public.newsletter_subscriptions enable row level security;
alter table public.newsletter_deliveries enable row level security;

revoke all on public.newsletter_subscriptions from anon;
revoke all on public.newsletter_deliveries from anon;
revoke insert, delete on public.newsletter_subscriptions from authenticated;
revoke insert, update, delete on public.newsletter_deliveries from authenticated;
grant select, update on public.newsletter_subscriptions to authenticated;
grant select on public.newsletter_deliveries to authenticated;

drop policy if exists "Readers view their newsletter preference" on public.newsletter_subscriptions;
drop policy if exists "Readers update their newsletter preference" on public.newsletter_subscriptions;
drop policy if exists "Owner reads newsletter deliveries" on public.newsletter_deliveries;

create policy "Readers view their newsletter preference"
on public.newsletter_subscriptions for select
to authenticated
using (
  (select auth.uid()) = user_id
  and lower(email) = lower(coalesce((select auth.jwt()) ->> 'email', ''))
);

create policy "Readers update their newsletter preference"
on public.newsletter_subscriptions for update
to authenticated
using ((select auth.uid()) = user_id)
with check (
  (select auth.uid()) = user_id
  and lower(email) = lower(coalesce((select auth.jwt()) ->> 'email', ''))
);

create policy "Owner reads newsletter deliveries"
on public.newsletter_deliveries for select
to authenticated
using ((select auth.uid()) = 'e21f3af3-0afb-41e4-a84f-5b8f10d7f37b'::uuid);

commit;
