-- Mind Over Matter professional blog upgrade
-- Run once in Supabase Dashboard > SQL Editor.
-- Owner UID: e21f3af3-0afb-41e4-a84f-5b8f10d7f37b

begin;

-- ---------------------------------------------------------------------------
-- 1. Extend posts for professional URLs, discovery, scheduling, and SEO.
-- ---------------------------------------------------------------------------

alter table public.posts
  add column if not exists slug text,
  add column if not exists category text not null default 'Psychology',
  add column if not exists summary text,
  add column if not exists featured boolean not null default false,
  add column if not exists updated_at timestamptz not null default now(),
  add column if not exists publish_at timestamptz,
  add column if not exists cover_image_url text;

update public.posts
set slug = coalesce(
  nullif(trim(both '-' from regexp_replace(lower(coalesce(title, '')), '[^a-z0-9]+', '-', 'g')), ''),
  'post'
) || '-' || id
where slug is null or slug = '';

alter table public.posts alter column slug set not null;
create unique index if not exists posts_slug_key on public.posts(slug);
create index if not exists posts_publication_idx
  on public.posts(published, publish_at, created_at desc);
create index if not exists posts_category_idx on public.posts(category);

create or replace function public.set_post_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_posts_updated_at on public.posts;
create trigger set_posts_updated_at
before update on public.posts
for each row execute function public.set_post_updated_at();

-- ---------------------------------------------------------------------------
-- 2. Reader profiles, likes, comments, and automatic profile creation.
-- ---------------------------------------------------------------------------

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null check (char_length(display_name) between 1 and 60),
  created_at timestamptz not null default now()
);

create table if not exists public.post_likes (
  post_id bigint not null references public.posts(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (post_id, user_id)
);

create index if not exists post_likes_post_idx on public.post_likes(post_id);

create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.posts(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  body text not null check (char_length(body) between 1 and 1200),
  approved boolean not null default true,
  created_at timestamptz not null default now()
);

create index if not exists comments_post_created_idx
  on public.comments(post_id, created_at);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, display_name)
  values (
    new.id,
    left(
      coalesce(
        nullif(trim(new.raw_user_meta_data ->> 'display_name'), ''),
        split_part(coalesce(new.email, 'Reader'), '@', 1),
        'Reader'
      ),
      60
    )
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

insert into public.profiles (id, display_name)
select
  id,
  left(
    coalesce(
      nullif(trim(raw_user_meta_data ->> 'display_name'), ''),
      split_part(coalesce(email, 'Reader'), '@', 1),
      'Reader'
    ),
    60
  )
from auth.users
on conflict (id) do nothing;

-- ---------------------------------------------------------------------------
-- 3. Automatic revision history for owner edits.
-- ---------------------------------------------------------------------------

create table if not exists public.post_revisions (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.posts(id) on delete cascade,
  title text,
  body text,
  slug text,
  category text,
  summary text,
  featured boolean,
  published boolean,
  publish_at timestamptz,
  cover_image_url text,
  revised_at timestamptz not null default now()
);

create index if not exists post_revisions_post_idx
  on public.post_revisions(post_id, revised_at desc);

create or replace function public.capture_post_revision()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.post_revisions (
    post_id, title, body, slug, category, summary,
    featured, published, publish_at, cover_image_url
  ) values (
    old.id, old.title, old.body, old.slug, old.category, old.summary,
    old.featured, old.published, old.publish_at, old.cover_image_url
  );
  return new;
end;
$$;

drop trigger if exists capture_posts_revision on public.posts;
create trigger capture_posts_revision
before update on public.posts
for each row execute function public.capture_post_revision();

-- ---------------------------------------------------------------------------
-- 4. Privileges and Row Level Security.
-- ---------------------------------------------------------------------------

alter table public.posts enable row level security;
alter table public.profiles enable row level security;
alter table public.post_likes enable row level security;
alter table public.comments enable row level security;
alter table public.post_revisions enable row level security;

grant select on public.posts, public.profiles, public.post_likes, public.comments to anon;
revoke insert, update, delete on public.posts, public.profiles, public.post_likes, public.comments from anon;

grant select, insert, update, delete on public.posts to authenticated;
grant select, insert, update on public.profiles to authenticated;
grant select, insert, delete on public.post_likes to authenticated;
grant select, insert, update, delete on public.comments to authenticated;
grant select on public.post_revisions to authenticated;
grant usage, select on sequence public.comments_id_seq to authenticated;
grant usage, select on sequence public.post_revisions_id_seq to authenticated;

do $$
declare
  target_table text;
  policy_row record;
begin
  foreach target_table in array array['posts','profiles','post_likes','comments','post_revisions']
  loop
    for policy_row in
      select policyname
      from pg_policies
      where schemaname = 'public' and tablename = target_table
    loop
      execute format('drop policy if exists %I on public.%I', policy_row.policyname, target_table);
    end loop;
  end loop;
end
$$;

create policy "Public reads released posts"
on public.posts for select
to anon, authenticated
using (
  published is true
  and (publish_at is null or publish_at <= now())
);

create policy "Owner reads all posts"
on public.posts for select
to authenticated
using ((select auth.uid()) = 'e21f3af3-0afb-41e4-a84f-5b8f10d7f37b'::uuid);

create policy "Owner creates posts"
on public.posts for insert
to authenticated
with check ((select auth.uid()) = 'e21f3af3-0afb-41e4-a84f-5b8f10d7f37b'::uuid);

create policy "Owner updates posts"
on public.posts for update
to authenticated
using ((select auth.uid()) = 'e21f3af3-0afb-41e4-a84f-5b8f10d7f37b'::uuid)
with check ((select auth.uid()) = 'e21f3af3-0afb-41e4-a84f-5b8f10d7f37b'::uuid);

create policy "Owner deletes posts"
on public.posts for delete
to authenticated
using ((select auth.uid()) = 'e21f3af3-0afb-41e4-a84f-5b8f10d7f37b'::uuid);

create policy "Profiles are public"
on public.profiles for select
to anon, authenticated
using (true);

create policy "Readers create their profile"
on public.profiles for insert
to authenticated
with check ((select auth.uid()) = id);

create policy "Readers update their profile"
on public.profiles for update
to authenticated
using ((select auth.uid()) = id)
with check ((select auth.uid()) = id);

create policy "Likes are public"
on public.post_likes for select
to anon, authenticated
using (true);

create policy "Readers like as themselves"
on public.post_likes for insert
to authenticated
with check (
  (select auth.uid()) = user_id
  and exists (
    select 1 from public.posts
    where posts.id = post_likes.post_id
      and posts.published is true
      and (posts.publish_at is null or posts.publish_at <= now())
  )
);

create policy "Readers remove their own likes"
on public.post_likes for delete
to authenticated
using ((select auth.uid()) = user_id);

create policy "Approved comments are public"
on public.comments for select
to anon, authenticated
using (
  approved is true
  or (select auth.uid()) = user_id
  or (select auth.uid()) = 'e21f3af3-0afb-41e4-a84f-5b8f10d7f37b'::uuid
);

create policy "Readers comment as themselves"
on public.comments for insert
to authenticated
with check (
  (select auth.uid()) = user_id
  and exists (
    select 1 from public.posts
    where posts.id = comments.post_id
      and posts.published is true
      and (posts.publish_at is null or posts.publish_at <= now())
  )
);

create policy "Readers edit their comments"
on public.comments for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy "Readers or owner delete comments"
on public.comments for delete
to authenticated
using (
  (select auth.uid()) = user_id
  or (select auth.uid()) = 'e21f3af3-0afb-41e4-a84f-5b8f10d7f37b'::uuid
);

create policy "Owner reads revisions"
on public.post_revisions for select
to authenticated
using ((select auth.uid()) = 'e21f3af3-0afb-41e4-a84f-5b8f10d7f37b'::uuid);

commit;
